week10/fruitstore-rails-tdd/config/routes.rb
Rails.application.routes.draw do

  resources :peaches
  # get 'fruits/index'
  resources :fruits

end

week10/fruitstore-rails-tdd/app/models/apple.rb
class Apple < Fruit

end

week10/fruitstore-rails-tdd/app/models/fruit.rb
class Fruit < ApplicationRecord

  belongs_to :shelf    #, optional: true

  validates :name, presence: true

  def squishy?
    true
  end
end

week10/fruitstore-rails-tdd/app/models/peach.rb
class Peach < ApplicationRecord
end

week10/fruitstore-rails-tdd/app/models/pear.rb
class Pear < Fruit
  def squishy?
    true
  end
end

week10/fruitstore-rails-tdd/app/models/shelf.rb
class Shelf < ApplicationRecord
  has_many :fruits
end

week10/fruitstore-rails-tdd/app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  def index
    @fruits = Fruit.all.reverse
    # puts "=" * 50
    # puts "CONTROLLER"

    respond_to do |format|
      format.html {} # Render the default template for this action
      format.json { render json: @fruits }
    end
  end

  def create
    @fruit = Fruit.new fruit_params

    if @fruit.save
      redirect_to @fruit
    else
      render :new
    end

  end

  private
  def fruit_params
    params.require(:fruit).permit(:name)
  end

end

week10/fruitstore-rails-tdd/app/controllers/peaches_controller.rb
class PeachesController < ApplicationController
  before_action :set_peach, only: [:show, :edit, :update, :destroy]

  # GET /peaches
  # GET /peaches.json
  def index
    @peaches = Peach.all
  end

  # GET /peaches/1
  # GET /peaches/1.json
  def show
  end

  # GET /peaches/new
  def new
    @peach = Peach.new
  end

  # GET /peaches/1/edit
  def edit
  end

  # POST /peaches
  # POST /peaches.json
  def create
    @peach = Peach.new(peach_params)

    respond_to do |format|
      if @peach.save
        format.html { redirect_to @peach, notice: 'Peach was successfully created.' }
        format.json { render :show, status: :created, location: @peach }
      else
        format.html { render :new }
        format.json { render json: @peach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peaches/1
  # PATCH/PUT /peaches/1.json
  def update
    respond_to do |format|
      if @peach.update(peach_params)
        format.html { redirect_to @peach, notice: 'Peach was successfully updated.' }
        format.json { render :show, status: :ok, location: @peach }
      else
        format.html { render :edit }
        format.json { render json: @peach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peaches/1
  # DELETE /peaches/1.json
  def destroy
    @peach.destroy
    respond_to do |format|
      format.html { redirect_to peaches_url, notice: 'Peach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peach
      @peach = Peach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peach_params
      params.require(:peach).permit(:name)
    end
end

week10/fruitstore-rails-tdd/app/helpers/fruits_helper.rb
module FruitsHelper
end

week10/fruitstore-rails-tdd/app/helpers/peaches_helper.rb
module PeachesHelper
end

week10/fruitstore-rails-tdd/app/views/fruits/index.html.erb
<h1>All Fruits</h1>
<ul>
<% @fruits.each do |f| %>
  <li> <%= f.name %> </li>
<% end %>
</ul>

week10/fruitstore-rails-tdd/app/views/peaches/_form.html.erb
<%= form_for(peach) do |f| %>
  <% if peach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peach.errors.count, "error") %> prohibited this peach from being saved:</h2>

      <ul>
      <% peach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week10/fruitstore-rails-tdd/app/views/peaches/edit.html.erb
<h1>Editing Peach</h1>

<%= render 'form', peach: @peach %>

<%= link_to 'Show', @peach %> |
<%= link_to 'Back', peaches_path %>

week10/fruitstore-rails-tdd/app/views/peaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peaches.each do |peach| %>
      <tr>
        <td><%= peach.name %></td>
        <td><%= link_to 'Show', peach %></td>
        <td><%= link_to 'Edit', edit_peach_path(peach) %></td>
        <td><%= link_to 'Destroy', peach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peach', new_peach_path %>

week10/fruitstore-rails-tdd/app/views/peaches/new.html.erb
<h1>New Peach</h1>

<%= render 'form', peach: @peach %>

<%= link_to 'Back', peaches_path %>

week10/fruitstore-rails-tdd/app/views/peaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @peach.name %>
</p>

<%= link_to 'Edit', edit_peach_path(@peach) %> |
<%= link_to 'Back', peaches_path %>